package com.kuhrusty.morbadscorepad;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.preference.CheckBoxPreference;
import android.preference.ListPreference;
import android.preference.Preference;
import android.preference.PreferenceActivity;
import android.preference.PreferenceCategory;
import android.preference.PreferenceFragment;
import android.preference.PreferenceManager;
import android.preference.SwitchPreference;
import android.support.v4.app.NavUtils;
import android.support.v7.app.ActionBar;
import android.view.MenuItem;

import com.kuhrusty.morbadscorepad.model.Expansion;
import com.kuhrusty.morbadscorepad.model.GameConfiguration;
import com.kuhrusty.morbadscorepad.model.dao.GameRepository;
import com.kuhrusty.morbadscorepad.model.dao.RepositoryFactory;

import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * A {@link PreferenceActivity} that presents a set of application settings. On
 * handset devices, settings are presented as a single list. On tablets,
 * settings are split by category, with category headers shown to the left of
 * the list of settings.
 * <p>
 * See <a href="http://developer.android.com/design/patterns/settings.html">
 * Android Design: Settings</a> for design guidelines and the <a
 * href="http://developer.android.com/guide/topics/ui/settings.html">Settings
 * API Guide</a> for more information on developing a Settings UI.
 */
public class SettingsActivity extends AppCompatPreferenceActivity {

    private static final String PREF_DATA_DIRECTORY = "pref_data_dir";

    /**
     * Generated by Android Studio.
     *
     * A preference value change listener that updates the preference's summary
     * to reflect its new value.
     */
    private static class OurPreferenceChangeListener implements Preference.OnPreferenceChangeListener {
        private Context context;
        private PreferenceCategory expansionPrefCat;
        private GameConfiguration gameConfig;
        private GameRepository grepos;
        public OurPreferenceChangeListener(Context context,
                                           PreferenceCategory expansionPrefCat,
                                           GameConfiguration gameConfig,
                                           GameRepository grepos) {
            this.context = context;
            this.expansionPrefCat = expansionPrefCat;
            this.gameConfig = gameConfig;
            this.grepos = grepos;
        }

        @Override
        public boolean onPreferenceChange(Preference preference, Object value) {
            String stringValue = value.toString();

            if (preference instanceof ListPreference) {
                // For list preferences, look up the correct display value in
                // the preference's 'entries' list.
                ListPreference listPreference = (ListPreference) preference;
                int index = listPreference.findIndexOfValue(stringValue);

                // Set the summary to reflect the new value.
                preference.setSummary(
                        index >= 0
                                ? listPreference.getEntries()[index]
                                : null);

            } else if ((preference instanceof CheckBoxPreference) ||
                       (preference instanceof SwitchPreference)) {
                //  we don't need a summary
            } else {
                // For all other preferences, set the summary to the value's
                // simple string representation.
                preference.setSummary(stringValue);
            }

            if (preference.getKey().equals(PREF_DATA_DIRECTORY)) {
                updateExpansionPrefs(context, expansionPrefCat, gameConfig, grepos);
            }
            return true;
        }
    };

    /**
     * Generated by Android Studio.
     *
     * Binds a preference's summary to its value. More specifically, when the
     * preference's value is changed, its summary (line of text below the
     * preference title) is updated to reflect the value. The summary is also
     * immediately updated upon calling this method. The exact display format is
     * dependent on the type of preference.
     */
    private static void bindPreferenceSummaryToValue(Preference.OnPreferenceChangeListener opcl,
                                                     Preference preference) {
        // Set the listener to watch for value changes.
        preference.setOnPreferenceChangeListener(opcl);

        // Trigger the listener immediately with the preference's
        // current value.
        manuallyTriggerPreferenceChange(opcl, preference);
    }

    private static void manuallyTriggerPreferenceChange(Preference.OnPreferenceChangeListener pcl,
                                                        Preference preference) {
        Object value = null;
        if ((preference instanceof CheckBoxPreference) ||
            (preference instanceof SwitchPreference)) {
            value = PreferenceManager
                    .getDefaultSharedPreferences(preference.getContext())
                    .getBoolean(preference.getKey(), false);
        } else {
            value = PreferenceManager
                    .getDefaultSharedPreferences(preference.getContext())
                    .getString(preference.getKey(), "");
        }
        pcl.onPreferenceChange(preference, value);
    }

    //  Make the list of expansion preferences match the list of expansions
    //  available for this game, and check/uncheck them based on the given
    //  gameConfig.
//no, don't bother with that last bit... we probably set up gameConfig based on the existing prefs!
    private static void updateExpansionPrefs(Context context,
                                             PreferenceCategory prefCat,
                                             GameConfiguration gameConfig,
                                             GameRepository grepos) {
        if ((prefCat == null) || (gameConfig == null)) return;  //  not much we can do
        List<Expansion> expansions = grepos.getExpansions(context, gameConfig);
        if (expansions == null) {
            return;  //  life is horrible, bail
        }
        //  first, get the list of existing preferences.
        Set<String> prefsToRemove = new TreeSet<>();
        for (int ii = 0; ii < prefCat.getPreferenceCount(); ++ii) {
            prefsToRemove.add(prefCat.getPreference(ii).getKey());
        }
        //  now, for each available expansion, add a preference if one doesn't
        //  already exist.
        for (Expansion exp : expansions) {
            String prefKey = gameConfig.expansionIDToPrefKey(exp.getID());
            if (prefCat.findPreference(prefKey) == null) {
                CheckBoxPreference cbp = new CheckBoxPreference(context);
                cbp.setKey(prefKey);
                cbp.setTitle(exp.getName());
                prefCat.addPreference(cbp);
            } else {
                //  we want to keep it.
                prefsToRemove.remove(prefKey);
            }
        }
        //  Now remove any which we didn't want to keep.
        for (String key : prefsToRemove) {
            prefCat.removePreference(prefCat.findPreference(key));
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Display the fragment as the main content.
        getFragmentManager().beginTransaction()
                .replace(android.R.id.content, new WurstPreferenceFragment())
                .commit();
        setupActionBar();
    }

    /**
     * Generated by Android Studio.
     *
     * Set up the {@link android.app.ActionBar}, if the API is available.
     */
    private void setupActionBar() {
        ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) {
            // Show the Up button in the action bar.
            actionBar.setDisplayHomeAsUpEnabled(true);
        }
    }

    @Override
    public boolean onMenuItemSelected(int featureId, MenuItem item) {
        int id = item.getItemId();
        if (id == android.R.id.home) {
            if (!super.onMenuItemSelected(featureId, item)) {
                NavUtils.navigateUpFromSameTask(this);
            }
            return true;
        }
        return super.onMenuItemSelected(featureId, item);
    }

    public static class WurstPreferenceFragment extends PreferenceFragment {
        private GameConfiguration gameConfig;
        private GameRepository grepos = RepositoryFactory.getGameRepository();
        private PreferenceCategory expansionPrefCat;

        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            addPreferencesFromResource(R.xml.preferences);

            gameConfig = new GameConfiguration(getActivity(), getPreferenceManager().getSharedPreferences(), grepos);

            //  ARGHH--if the Android Design guidelines specify this, then why
            //  don't the Android libraries just $%#$@!! do this!?
            //  // Bind the summaries of EditText/List/Dialog/Ringtone preferences
            //  // to their values. When their values change, their summaries are
            //  // updated to reflect the new value, per the Android Design
            //  // guidelines.
            SharedPreferences prefs = getPreferenceManager().getSharedPreferences();
            expansionPrefCat = (PreferenceCategory)(findPreference("pref_expansions"));
            OurPreferenceChangeListener opcl = new OurPreferenceChangeListener(getActivity(), expansionPrefCat, gameConfig, grepos);
            updateExpansionPrefs(getActivity(), expansionPrefCat, gameConfig, grepos);
            for (String prefKey : prefs.getAll().keySet()) {
                Preference pref = findPreference(prefKey);
                if (pref != null) {
                    bindPreferenceSummaryToValue(opcl, pref);
                }
            }
        }
    }
}
